### ISSUE TITLE
Error to build apk with: phosphor_flutter: ^2.0.0

### ISSUE THREAD

**Issue by h1amza** [phosphor-icons/flutter#25]
![Capture0](https://github.com/phosphor-icons/flutter/assets/32615603/1649ce15-c923-4e65-a284-e91f4b614042)

**Comment by h1amza** [comment]
i think this issue it's sumulaire with #20  and #24

**Comment by karebmusu** [comment]
temporary solution use flutter build apk --release --no-tree-shake-icons
its work for me

**Comment by maks** [comment]
`-no-tree-shake-icons` is not really a good even _temporary_ solution.
Ideally it would be good for a new release to be published on pub.dev with the commits that have been merged since April 5 when 2.0.0 was published, but for now using a Git url instead of 2.0.0 in your `pubspec.yaml` should work.
